/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as OrientationRouteImport } from './routes/orientation'
import { Route as ProRouteImport } from './routes/pro'
import { Route as RecoveryCodesRouteImport } from './routes/recovery-codes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminBetaRouteImport } from './routes/admin.beta'
import { Route as AdminProfessionalsRouteImport } from './routes/admin.professionals'
import { Route as ApiRemindersRouteImport } from './routes/api.reminders'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppClarifyRouteImport } from './routes/app.clarify'
import { Route as AppConsultationsRouteImport } from './routes/app.consultations'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppEvidenceMapRouteImport } from './routes/app.evidence-map'
import { Route as AppQuestionsRouteImport } from './routes/app.questions'
import { Route as AppReviewRouteImport } from './routes/app.review'
import { Route as AppReviewDetailsRouteImport } from './routes/app.review-details'
import { Route as AppSharingRouteImport } from './routes/app.sharing'
import { Route as AppStoryRouteImport } from './routes/app.story'
import { Route as AppTimelineRouteImport } from './routes/app.timeline'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityFeedRouteImport } from './routes/community.feed'
import { Route as CommunityFeedbackRouteImport } from './routes/community.feedback'
import { Route as CommunityMessagesRouteImport } from './routes/community.messages'
import { Route as CommunityModerationRouteImport } from './routes/community.moderation'
import { Route as CommunityNewRouteImport } from './routes/community.new'
import { Route as CommunityNotificationsRouteImport } from './routes/community.notifications'
import { Route as CommunityProfileRouteImport } from './routes/community.profile'
import { Route as CommunityRoomsRouteImport } from './routes/community.rooms'
import { Route as CommunitySearchRouteImport } from './routes/community.search'
import { Route as DebugGuardrailsRouteImport } from './routes/debug.guardrails'
import { Route as ProAvailabilityRouteImport } from './routes/pro.availability'
import { Route as ProCalibrationRouteImport } from './routes/pro.calibration'
import { Route as ProCasesRouteImport } from './routes/pro.cases'
import { Route as ProVerificationRouteImport } from './routes/pro.verification'
import { Route as AppDocumentsDocumentIdRouteImport } from './routes/app.documents.$documentId'
import { Route as AppStoryIndexRouteImport } from './routes/app.story.index'
import { Route as AppStorySectionRouteImport } from './routes/app.story.$section'
import { Route as AppStoryImportRouteImport } from './routes/app.story.import'
import { Route as CommunityCSlugRouteImport } from './routes/community.c.$slug'
import { Route as CommunityMessagesIndexRouteImport } from './routes/community.messages.index'
import { Route as CommunityMessagesThreadIdRouteImport } from './routes/community.messages.$threadId'
import { Route as CommunityRoomsIndexRouteImport } from './routes/community.rooms.index'
import { Route as CommunityRoomsSlugRouteImport } from './routes/community.rooms.$slug'
import { Route as CommunityTTopicIdRouteImport } from './routes/community.t.$topicId'
import { Route as ProCasesCaseIdRouteImport } from './routes/pro.cases.$caseId'
import { Route as AppStorySectionHistoryPromptRouteImport } from './routes/app.story.$section.history.$prompt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientationRoute = OrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryCodesRoute = RecoveryCodesRouteImport.update({
  id: '/recovery-codes',
  path: '/recovery-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBetaRoute = AdminBetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfessionalsRoute = AdminProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => AdminRoute,
} as any)
const ApiRemindersRoute = ApiRemindersRouteImport.update({
  id: '/api/reminders',
  path: '/api/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppClarifyRoute = AppClarifyRouteImport.update({
  id: '/clarify',
  path: '/clarify',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultationsRoute = AppConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceMapRoute = AppEvidenceMapRouteImport.update({
  id: '/evidence-map',
  path: '/evidence-map',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionsRoute = AppQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewDetailsRoute = AppReviewDetailsRouteImport.update({
  id: '/review-details',
  path: '/review-details',
  getParentRoute: () => AppRoute,
} as any)
const AppSharingRoute = AppSharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => AppRoute,
} as any)
const AppStoryRoute = AppStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityFeedRoute = CommunityFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityFeedbackRoute = CommunityFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityMessagesRoute = CommunityMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityModerationRoute = CommunityModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityNewRoute = CommunityNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityNotificationsRoute = CommunityNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityProfileRoute = CommunityProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityRoomsRoute = CommunityRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunitySearchRoute = CommunitySearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => CommunityRoute,
} as any)
const DebugGuardrailsRoute = DebugGuardrailsRouteImport.update({
  id: '/debug/guardrails',
  path: '/debug/guardrails',
  getParentRoute: () => rootRouteImport,
} as any)
const ProAvailabilityRoute = ProAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => ProRoute,
} as any)
const ProCalibrationRoute = ProCalibrationRouteImport.update({
  id: '/calibration',
  path: '/calibration',
  getParentRoute: () => ProRoute,
} as any)
const ProCasesRoute = ProCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => ProRoute,
} as any)
const ProVerificationRoute = ProVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => ProRoute,
} as any)
const AppDocumentsDocumentIdRoute = AppDocumentsDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AppStoryIndexRoute = AppStoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStoryRoute,
} as any)
const AppStorySectionRoute = AppStorySectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppStoryRoute,
} as any)
const AppStoryImportRoute = AppStoryImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppStoryRoute,
} as any)
const CommunityCSlugRoute = CommunityCSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityMessagesIndexRoute = CommunityMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityMessagesRoute,
} as any)
const CommunityMessagesThreadIdRoute =
  CommunityMessagesThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => CommunityMessagesRoute,
  } as any)
const CommunityRoomsIndexRoute = CommunityRoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoomsRoute,
} as any)
const CommunityRoomsSlugRoute = CommunityRoomsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CommunityRoomsRoute,
} as any)
const CommunityTTopicIdRoute = CommunityTTopicIdRouteImport.update({
  id: '/t/$topicId',
  path: '/t/$topicId',
  getParentRoute: () => CommunityRoute,
} as any)
const ProCasesCaseIdRoute = ProCasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => ProCasesRoute,
} as any)
const AppStorySectionHistoryPromptRoute =
  AppStorySectionHistoryPromptRouteImport.update({
    id: '/history/$prompt',
    path: '/history/$prompt',
    getParentRoute: () => AppStorySectionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/consent': typeof ConsentRoute
  '/orientation': typeof OrientationRoute
  '/pro': typeof ProRouteWithChildren
  '/recovery-codes': typeof RecoveryCodesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/beta': typeof AdminBetaRoute
  '/admin/professionals': typeof AdminProfessionalsRoute
  '/api/reminders': typeof ApiRemindersRoute
  '/app/activity': typeof AppActivityRoute
  '/app/clarify': typeof AppClarifyRoute
  '/app/consultations': typeof AppConsultationsRoute
  '/app/documents': typeof AppDocumentsRouteWithChildren
  '/app/evidence-map': typeof AppEvidenceMapRoute
  '/app/questions': typeof AppQuestionsRoute
  '/app/review': typeof AppReviewRoute
  '/app/review-details': typeof AppReviewDetailsRoute
  '/app/sharing': typeof AppSharingRoute
  '/app/story': typeof AppStoryRouteWithChildren
  '/app/timeline': typeof AppTimelineRoute
  '/community/feed': typeof CommunityFeedRoute
  '/community/feedback': typeof CommunityFeedbackRoute
  '/community/messages': typeof CommunityMessagesRouteWithChildren
  '/community/moderation': typeof CommunityModerationRoute
  '/community/new': typeof CommunityNewRoute
  '/community/notifications': typeof CommunityNotificationsRoute
  '/community/profile': typeof CommunityProfileRoute
  '/community/rooms': typeof CommunityRoomsRouteWithChildren
  '/community/search': typeof CommunitySearchRoute
  '/debug/guardrails': typeof DebugGuardrailsRoute
  '/pro/availability': typeof ProAvailabilityRoute
  '/pro/calibration': typeof ProCalibrationRoute
  '/pro/cases': typeof ProCasesRouteWithChildren
  '/pro/verification': typeof ProVerificationRoute
  '/community/': typeof CommunityIndexRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/story/$section': typeof AppStorySectionRouteWithChildren
  '/app/story/import': typeof AppStoryImportRoute
  '/community/c/$slug': typeof CommunityCSlugRoute
  '/community/messages/$threadId': typeof CommunityMessagesThreadIdRoute
  '/community/rooms/$slug': typeof CommunityRoomsSlugRoute
  '/community/t/$topicId': typeof CommunityTTopicIdRoute
  '/pro/cases/$caseId': typeof ProCasesCaseIdRoute
  '/app/story/': typeof AppStoryIndexRoute
  '/community/messages/': typeof CommunityMessagesIndexRoute
  '/community/rooms/': typeof CommunityRoomsIndexRoute
  '/app/story/$section/history/$prompt': typeof AppStorySectionHistoryPromptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/consent': typeof ConsentRoute
  '/orientation': typeof OrientationRoute
  '/pro': typeof ProRouteWithChildren
  '/recovery-codes': typeof RecoveryCodesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/beta': typeof AdminBetaRoute
  '/admin/professionals': typeof AdminProfessionalsRoute
  '/api/reminders': typeof ApiRemindersRoute
  '/app/activity': typeof AppActivityRoute
  '/app/clarify': typeof AppClarifyRoute
  '/app/consultations': typeof AppConsultationsRoute
  '/app/documents': typeof AppDocumentsRouteWithChildren
  '/app/evidence-map': typeof AppEvidenceMapRoute
  '/app/questions': typeof AppQuestionsRoute
  '/app/review': typeof AppReviewRoute
  '/app/review-details': typeof AppReviewDetailsRoute
  '/app/sharing': typeof AppSharingRoute
  '/app/timeline': typeof AppTimelineRoute
  '/community/feed': typeof CommunityFeedRoute
  '/community/feedback': typeof CommunityFeedbackRoute
  '/community/moderation': typeof CommunityModerationRoute
  '/community/new': typeof CommunityNewRoute
  '/community/notifications': typeof CommunityNotificationsRoute
  '/community/profile': typeof CommunityProfileRoute
  '/community/search': typeof CommunitySearchRoute
  '/debug/guardrails': typeof DebugGuardrailsRoute
  '/pro/availability': typeof ProAvailabilityRoute
  '/pro/calibration': typeof ProCalibrationRoute
  '/pro/cases': typeof ProCasesRouteWithChildren
  '/pro/verification': typeof ProVerificationRoute
  '/community': typeof CommunityIndexRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/story/$section': typeof AppStorySectionRouteWithChildren
  '/app/story/import': typeof AppStoryImportRoute
  '/community/c/$slug': typeof CommunityCSlugRoute
  '/community/messages/$threadId': typeof CommunityMessagesThreadIdRoute
  '/community/rooms/$slug': typeof CommunityRoomsSlugRoute
  '/community/t/$topicId': typeof CommunityTTopicIdRoute
  '/pro/cases/$caseId': typeof ProCasesCaseIdRoute
  '/app/story': typeof AppStoryIndexRoute
  '/community/messages': typeof CommunityMessagesIndexRoute
  '/community/rooms': typeof CommunityRoomsIndexRoute
  '/app/story/$section/history/$prompt': typeof AppStorySectionHistoryPromptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/consent': typeof ConsentRoute
  '/orientation': typeof OrientationRoute
  '/pro': typeof ProRouteWithChildren
  '/recovery-codes': typeof RecoveryCodesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/beta': typeof AdminBetaRoute
  '/admin/professionals': typeof AdminProfessionalsRoute
  '/api/reminders': typeof ApiRemindersRoute
  '/app/activity': typeof AppActivityRoute
  '/app/clarify': typeof AppClarifyRoute
  '/app/consultations': typeof AppConsultationsRoute
  '/app/documents': typeof AppDocumentsRouteWithChildren
  '/app/evidence-map': typeof AppEvidenceMapRoute
  '/app/questions': typeof AppQuestionsRoute
  '/app/review': typeof AppReviewRoute
  '/app/review-details': typeof AppReviewDetailsRoute
  '/app/sharing': typeof AppSharingRoute
  '/app/story': typeof AppStoryRouteWithChildren
  '/app/timeline': typeof AppTimelineRoute
  '/community/feed': typeof CommunityFeedRoute
  '/community/feedback': typeof CommunityFeedbackRoute
  '/community/messages': typeof CommunityMessagesRouteWithChildren
  '/community/moderation': typeof CommunityModerationRoute
  '/community/new': typeof CommunityNewRoute
  '/community/notifications': typeof CommunityNotificationsRoute
  '/community/profile': typeof CommunityProfileRoute
  '/community/rooms': typeof CommunityRoomsRouteWithChildren
  '/community/search': typeof CommunitySearchRoute
  '/debug/guardrails': typeof DebugGuardrailsRoute
  '/pro/availability': typeof ProAvailabilityRoute
  '/pro/calibration': typeof ProCalibrationRoute
  '/pro/cases': typeof ProCasesRouteWithChildren
  '/pro/verification': typeof ProVerificationRoute
  '/community/': typeof CommunityIndexRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/story/$section': typeof AppStorySectionRouteWithChildren
  '/app/story/import': typeof AppStoryImportRoute
  '/community/c/$slug': typeof CommunityCSlugRoute
  '/community/messages/$threadId': typeof CommunityMessagesThreadIdRoute
  '/community/rooms/$slug': typeof CommunityRoomsSlugRoute
  '/community/t/$topicId': typeof CommunityTTopicIdRoute
  '/pro/cases/$caseId': typeof ProCasesCaseIdRoute
  '/app/story/': typeof AppStoryIndexRoute
  '/community/messages/': typeof CommunityMessagesIndexRoute
  '/community/rooms/': typeof CommunityRoomsIndexRoute
  '/app/story/$section/history/$prompt': typeof AppStorySectionHistoryPromptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/community'
    | '/consent'
    | '/orientation'
    | '/pro'
    | '/recovery-codes'
    | '/sitemap.xml'
    | '/admin/beta'
    | '/admin/professionals'
    | '/api/reminders'
    | '/app/activity'
    | '/app/clarify'
    | '/app/consultations'
    | '/app/documents'
    | '/app/evidence-map'
    | '/app/questions'
    | '/app/review'
    | '/app/review-details'
    | '/app/sharing'
    | '/app/story'
    | '/app/timeline'
    | '/community/feed'
    | '/community/feedback'
    | '/community/messages'
    | '/community/moderation'
    | '/community/new'
    | '/community/notifications'
    | '/community/profile'
    | '/community/rooms'
    | '/community/search'
    | '/debug/guardrails'
    | '/pro/availability'
    | '/pro/calibration'
    | '/pro/cases'
    | '/pro/verification'
    | '/community/'
    | '/app/documents/$documentId'
    | '/app/story/$section'
    | '/app/story/import'
    | '/community/c/$slug'
    | '/community/messages/$threadId'
    | '/community/rooms/$slug'
    | '/community/t/$topicId'
    | '/pro/cases/$caseId'
    | '/app/story/'
    | '/community/messages/'
    | '/community/rooms/'
    | '/app/story/$section/history/$prompt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/consent'
    | '/orientation'
    | '/pro'
    | '/recovery-codes'
    | '/sitemap.xml'
    | '/admin/beta'
    | '/admin/professionals'
    | '/api/reminders'
    | '/app/activity'
    | '/app/clarify'
    | '/app/consultations'
    | '/app/documents'
    | '/app/evidence-map'
    | '/app/questions'
    | '/app/review'
    | '/app/review-details'
    | '/app/sharing'
    | '/app/timeline'
    | '/community/feed'
    | '/community/feedback'
    | '/community/moderation'
    | '/community/new'
    | '/community/notifications'
    | '/community/profile'
    | '/community/search'
    | '/debug/guardrails'
    | '/pro/availability'
    | '/pro/calibration'
    | '/pro/cases'
    | '/pro/verification'
    | '/community'
    | '/app/documents/$documentId'
    | '/app/story/$section'
    | '/app/story/import'
    | '/community/c/$slug'
    | '/community/messages/$threadId'
    | '/community/rooms/$slug'
    | '/community/t/$topicId'
    | '/pro/cases/$caseId'
    | '/app/story'
    | '/community/messages'
    | '/community/rooms'
    | '/app/story/$section/history/$prompt'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/community'
    | '/consent'
    | '/orientation'
    | '/pro'
    | '/recovery-codes'
    | '/sitemap.xml'
    | '/admin/beta'
    | '/admin/professionals'
    | '/api/reminders'
    | '/app/activity'
    | '/app/clarify'
    | '/app/consultations'
    | '/app/documents'
    | '/app/evidence-map'
    | '/app/questions'
    | '/app/review'
    | '/app/review-details'
    | '/app/sharing'
    | '/app/story'
    | '/app/timeline'
    | '/community/feed'
    | '/community/feedback'
    | '/community/messages'
    | '/community/moderation'
    | '/community/new'
    | '/community/notifications'
    | '/community/profile'
    | '/community/rooms'
    | '/community/search'
    | '/debug/guardrails'
    | '/pro/availability'
    | '/pro/calibration'
    | '/pro/cases'
    | '/pro/verification'
    | '/community/'
    | '/app/documents/$documentId'
    | '/app/story/$section'
    | '/app/story/import'
    | '/community/c/$slug'
    | '/community/messages/$threadId'
    | '/community/rooms/$slug'
    | '/community/t/$topicId'
    | '/pro/cases/$caseId'
    | '/app/story/'
    | '/community/messages/'
    | '/community/rooms/'
    | '/app/story/$section/history/$prompt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  OrientationRoute: typeof OrientationRoute
  ProRoute: typeof ProRouteWithChildren
  RecoveryCodesRoute: typeof RecoveryCodesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiRemindersRoute: typeof ApiRemindersRoute
  DebugGuardrailsRoute: typeof DebugGuardrailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientation': {
      id: '/orientation'
      path: '/orientation'
      fullPath: '/orientation'
      preLoaderRoute: typeof OrientationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-codes': {
      id: '/recovery-codes'
      path: '/recovery-codes'
      fullPath: '/recovery-codes'
      preLoaderRoute: typeof RecoveryCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/beta': {
      id: '/admin/beta'
      path: '/beta'
      fullPath: '/admin/beta'
      preLoaderRoute: typeof AdminBetaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/professionals': {
      id: '/admin/professionals'
      path: '/professionals'
      fullPath: '/admin/professionals'
      preLoaderRoute: typeof AdminProfessionalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/reminders': {
      id: '/api/reminders'
      path: '/api/reminders'
      fullPath: '/api/reminders'
      preLoaderRoute: typeof ApiRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clarify': {
      id: '/app/clarify'
      path: '/clarify'
      fullPath: '/app/clarify'
      preLoaderRoute: typeof AppClarifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consultations': {
      id: '/app/consultations'
      path: '/consultations'
      fullPath: '/app/consultations'
      preLoaderRoute: typeof AppConsultationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evidence-map': {
      id: '/app/evidence-map'
      path: '/evidence-map'
      fullPath: '/app/evidence-map'
      preLoaderRoute: typeof AppEvidenceMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/questions': {
      id: '/app/questions'
      path: '/questions'
      fullPath: '/app/questions'
      preLoaderRoute: typeof AppQuestionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review-details': {
      id: '/app/review-details'
      path: '/review-details'
      fullPath: '/app/review-details'
      preLoaderRoute: typeof AppReviewDetailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sharing': {
      id: '/app/sharing'
      path: '/sharing'
      fullPath: '/app/sharing'
      preLoaderRoute: typeof AppSharingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/story': {
      id: '/app/story'
      path: '/story'
      fullPath: '/app/story'
      preLoaderRoute: typeof AppStoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timeline': {
      id: '/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/feed': {
      id: '/community/feed'
      path: '/feed'
      fullPath: '/community/feed'
      preLoaderRoute: typeof CommunityFeedRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/feedback': {
      id: '/community/feedback'
      path: '/feedback'
      fullPath: '/community/feedback'
      preLoaderRoute: typeof CommunityFeedbackRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/messages': {
      id: '/community/messages'
      path: '/messages'
      fullPath: '/community/messages'
      preLoaderRoute: typeof CommunityMessagesRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/moderation': {
      id: '/community/moderation'
      path: '/moderation'
      fullPath: '/community/moderation'
      preLoaderRoute: typeof CommunityModerationRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/new': {
      id: '/community/new'
      path: '/new'
      fullPath: '/community/new'
      preLoaderRoute: typeof CommunityNewRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/notifications': {
      id: '/community/notifications'
      path: '/notifications'
      fullPath: '/community/notifications'
      preLoaderRoute: typeof CommunityNotificationsRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/profile': {
      id: '/community/profile'
      path: '/profile'
      fullPath: '/community/profile'
      preLoaderRoute: typeof CommunityProfileRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/rooms': {
      id: '/community/rooms'
      path: '/rooms'
      fullPath: '/community/rooms'
      preLoaderRoute: typeof CommunityRoomsRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/search': {
      id: '/community/search'
      path: '/search'
      fullPath: '/community/search'
      preLoaderRoute: typeof CommunitySearchRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/debug/guardrails': {
      id: '/debug/guardrails'
      path: '/debug/guardrails'
      fullPath: '/debug/guardrails'
      preLoaderRoute: typeof DebugGuardrailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/availability': {
      id: '/pro/availability'
      path: '/availability'
      fullPath: '/pro/availability'
      preLoaderRoute: typeof ProAvailabilityRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/calibration': {
      id: '/pro/calibration'
      path: '/calibration'
      fullPath: '/pro/calibration'
      preLoaderRoute: typeof ProCalibrationRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/cases': {
      id: '/pro/cases'
      path: '/cases'
      fullPath: '/pro/cases'
      preLoaderRoute: typeof ProCasesRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/verification': {
      id: '/pro/verification'
      path: '/verification'
      fullPath: '/pro/verification'
      preLoaderRoute: typeof ProVerificationRouteImport
      parentRoute: typeof ProRoute
    }
    '/app/documents/$documentId': {
      id: '/app/documents/$documentId'
      path: '/$documentId'
      fullPath: '/app/documents/$documentId'
      preLoaderRoute: typeof AppDocumentsDocumentIdRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/app/story/': {
      id: '/app/story/'
      path: '/'
      fullPath: '/app/story/'
      preLoaderRoute: typeof AppStoryIndexRouteImport
      parentRoute: typeof AppStoryRoute
    }
    '/app/story/$section': {
      id: '/app/story/$section'
      path: '/$section'
      fullPath: '/app/story/$section'
      preLoaderRoute: typeof AppStorySectionRouteImport
      parentRoute: typeof AppStoryRoute
    }
    '/app/story/import': {
      id: '/app/story/import'
      path: '/import'
      fullPath: '/app/story/import'
      preLoaderRoute: typeof AppStoryImportRouteImport
      parentRoute: typeof AppStoryRoute
    }
    '/community/c/$slug': {
      id: '/community/c/$slug'
      path: '/c/$slug'
      fullPath: '/community/c/$slug'
      preLoaderRoute: typeof CommunityCSlugRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/messages/': {
      id: '/community/messages/'
      path: '/'
      fullPath: '/community/messages/'
      preLoaderRoute: typeof CommunityMessagesIndexRouteImport
      parentRoute: typeof CommunityMessagesRoute
    }
    '/community/messages/$threadId': {
      id: '/community/messages/$threadId'
      path: '/$threadId'
      fullPath: '/community/messages/$threadId'
      preLoaderRoute: typeof CommunityMessagesThreadIdRouteImport
      parentRoute: typeof CommunityMessagesRoute
    }
    '/community/rooms/': {
      id: '/community/rooms/'
      path: '/'
      fullPath: '/community/rooms/'
      preLoaderRoute: typeof CommunityRoomsIndexRouteImport
      parentRoute: typeof CommunityRoomsRoute
    }
    '/community/rooms/$slug': {
      id: '/community/rooms/$slug'
      path: '/$slug'
      fullPath: '/community/rooms/$slug'
      preLoaderRoute: typeof CommunityRoomsSlugRouteImport
      parentRoute: typeof CommunityRoomsRoute
    }
    '/community/t/$topicId': {
      id: '/community/t/$topicId'
      path: '/t/$topicId'
      fullPath: '/community/t/$topicId'
      preLoaderRoute: typeof CommunityTTopicIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/pro/cases/$caseId': {
      id: '/pro/cases/$caseId'
      path: '/$caseId'
      fullPath: '/pro/cases/$caseId'
      preLoaderRoute: typeof ProCasesCaseIdRouteImport
      parentRoute: typeof ProCasesRoute
    }
    '/app/story/$section/history/$prompt': {
      id: '/app/story/$section/history/$prompt'
      path: '/history/$prompt'
      fullPath: '/app/story/$section/history/$prompt'
      preLoaderRoute: typeof AppStorySectionHistoryPromptRouteImport
      parentRoute: typeof AppStorySectionRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBetaRoute: typeof AdminBetaRoute
  AdminProfessionalsRoute: typeof AdminProfessionalsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBetaRoute: AdminBetaRoute,
  AdminProfessionalsRoute: AdminProfessionalsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppDocumentsRouteChildren {
  AppDocumentsDocumentIdRoute: typeof AppDocumentsDocumentIdRoute
}

const AppDocumentsRouteChildren: AppDocumentsRouteChildren = {
  AppDocumentsDocumentIdRoute: AppDocumentsDocumentIdRoute,
}

const AppDocumentsRouteWithChildren = AppDocumentsRoute._addFileChildren(
  AppDocumentsRouteChildren,
)

interface AppStorySectionRouteChildren {
  AppStorySectionHistoryPromptRoute: typeof AppStorySectionHistoryPromptRoute
}

const AppStorySectionRouteChildren: AppStorySectionRouteChildren = {
  AppStorySectionHistoryPromptRoute: AppStorySectionHistoryPromptRoute,
}

const AppStorySectionRouteWithChildren = AppStorySectionRoute._addFileChildren(
  AppStorySectionRouteChildren,
)

interface AppStoryRouteChildren {
  AppStorySectionRoute: typeof AppStorySectionRouteWithChildren
  AppStoryImportRoute: typeof AppStoryImportRoute
  AppStoryIndexRoute: typeof AppStoryIndexRoute
}

const AppStoryRouteChildren: AppStoryRouteChildren = {
  AppStorySectionRoute: AppStorySectionRouteWithChildren,
  AppStoryImportRoute: AppStoryImportRoute,
  AppStoryIndexRoute: AppStoryIndexRoute,
}

const AppStoryRouteWithChildren = AppStoryRoute._addFileChildren(
  AppStoryRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppClarifyRoute: typeof AppClarifyRoute
  AppConsultationsRoute: typeof AppConsultationsRoute
  AppDocumentsRoute: typeof AppDocumentsRouteWithChildren
  AppEvidenceMapRoute: typeof AppEvidenceMapRoute
  AppQuestionsRoute: typeof AppQuestionsRoute
  AppReviewRoute: typeof AppReviewRoute
  AppReviewDetailsRoute: typeof AppReviewDetailsRoute
  AppSharingRoute: typeof AppSharingRoute
  AppStoryRoute: typeof AppStoryRouteWithChildren
  AppTimelineRoute: typeof AppTimelineRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppClarifyRoute: AppClarifyRoute,
  AppConsultationsRoute: AppConsultationsRoute,
  AppDocumentsRoute: AppDocumentsRouteWithChildren,
  AppEvidenceMapRoute: AppEvidenceMapRoute,
  AppQuestionsRoute: AppQuestionsRoute,
  AppReviewRoute: AppReviewRoute,
  AppReviewDetailsRoute: AppReviewDetailsRoute,
  AppSharingRoute: AppSharingRoute,
  AppStoryRoute: AppStoryRouteWithChildren,
  AppTimelineRoute: AppTimelineRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CommunityMessagesRouteChildren {
  CommunityMessagesThreadIdRoute: typeof CommunityMessagesThreadIdRoute
  CommunityMessagesIndexRoute: typeof CommunityMessagesIndexRoute
}

const CommunityMessagesRouteChildren: CommunityMessagesRouteChildren = {
  CommunityMessagesThreadIdRoute: CommunityMessagesThreadIdRoute,
  CommunityMessagesIndexRoute: CommunityMessagesIndexRoute,
}

const CommunityMessagesRouteWithChildren =
  CommunityMessagesRoute._addFileChildren(CommunityMessagesRouteChildren)

interface CommunityRoomsRouteChildren {
  CommunityRoomsSlugRoute: typeof CommunityRoomsSlugRoute
  CommunityRoomsIndexRoute: typeof CommunityRoomsIndexRoute
}

const CommunityRoomsRouteChildren: CommunityRoomsRouteChildren = {
  CommunityRoomsSlugRoute: CommunityRoomsSlugRoute,
  CommunityRoomsIndexRoute: CommunityRoomsIndexRoute,
}

const CommunityRoomsRouteWithChildren = CommunityRoomsRoute._addFileChildren(
  CommunityRoomsRouteChildren,
)

interface CommunityRouteChildren {
  CommunityFeedRoute: typeof CommunityFeedRoute
  CommunityFeedbackRoute: typeof CommunityFeedbackRoute
  CommunityMessagesRoute: typeof CommunityMessagesRouteWithChildren
  CommunityModerationRoute: typeof CommunityModerationRoute
  CommunityNewRoute: typeof CommunityNewRoute
  CommunityNotificationsRoute: typeof CommunityNotificationsRoute
  CommunityProfileRoute: typeof CommunityProfileRoute
  CommunityRoomsRoute: typeof CommunityRoomsRouteWithChildren
  CommunitySearchRoute: typeof CommunitySearchRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  CommunityCSlugRoute: typeof CommunityCSlugRoute
  CommunityTTopicIdRoute: typeof CommunityTTopicIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityFeedRoute: CommunityFeedRoute,
  CommunityFeedbackRoute: CommunityFeedbackRoute,
  CommunityMessagesRoute: CommunityMessagesRouteWithChildren,
  CommunityModerationRoute: CommunityModerationRoute,
  CommunityNewRoute: CommunityNewRoute,
  CommunityNotificationsRoute: CommunityNotificationsRoute,
  CommunityProfileRoute: CommunityProfileRoute,
  CommunityRoomsRoute: CommunityRoomsRouteWithChildren,
  CommunitySearchRoute: CommunitySearchRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  CommunityCSlugRoute: CommunityCSlugRoute,
  CommunityTTopicIdRoute: CommunityTTopicIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface ProCasesRouteChildren {
  ProCasesCaseIdRoute: typeof ProCasesCaseIdRoute
}

const ProCasesRouteChildren: ProCasesRouteChildren = {
  ProCasesCaseIdRoute: ProCasesCaseIdRoute,
}

const ProCasesRouteWithChildren = ProCasesRoute._addFileChildren(
  ProCasesRouteChildren,
)

interface ProRouteChildren {
  ProAvailabilityRoute: typeof ProAvailabilityRoute
  ProCalibrationRoute: typeof ProCalibrationRoute
  ProCasesRoute: typeof ProCasesRouteWithChildren
  ProVerificationRoute: typeof ProVerificationRoute
}

const ProRouteChildren: ProRouteChildren = {
  ProAvailabilityRoute: ProAvailabilityRoute,
  ProCalibrationRoute: ProCalibrationRoute,
  ProCasesRoute: ProCasesRouteWithChildren,
  ProVerificationRoute: ProVerificationRoute,
}

const ProRouteWithChildren = ProRoute._addFileChildren(ProRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRouteWithChildren,
  ConsentRoute: ConsentRoute,
  OrientationRoute: OrientationRoute,
  ProRoute: ProRouteWithChildren,
  RecoveryCodesRoute: RecoveryCodesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiRemindersRoute: ApiRemindersRoute,
  DebugGuardrailsRoute: DebugGuardrailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
